### ISSUE TITLE
Auth Checklist MVP

### ISSUE THREAD

**Issue by jamestouri** [jamestouri/toGather#2]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)

**Comment by ronilbhatia** [comment]
![screen shot 2018-10-11 at 9 21 02 am](https://user-images.githubusercontent.com/32026924/46818815-f5c42280-cd36-11e8-8aa8-a40cf5a7d063.png)
![screen shot 2018-10-11 at 9 20 18 am](https://user-images.githubusercontent.com/32026924/46818814-f5c42280-cd36-11e8-9fae-ad3bfe40ab98.png)

* The image on your site doesn't seem to span the whole width of the page (there's like 1cm of white on the left).
* Needs demo login - you can include this anywhere, main page, signup page or login page or all! The easier it is for recruiters to find the demo login button the better.
* I would encourage adding some :hover/:focus CSS effects on buttons and links throughout. This will make the user experience on your site a lot better. For instance, on the main sign-up button on your splash page, notice how on Meetup's real site the red becomes fuller when you hover over the button.
* Need to add error rendering
* Need to have redirect so that when I go to a random route it redirects me to main page

**Comment by ronilbhatia** [comment]
Looks good. Please fix the log out button so that it doesn't look like a standard HTML button and I'll close out this issue :)
